name: Deploy to Staging Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          rustup update stable
          rustup default stable

      - name: build
        run: cargo build

      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_STAGING }}
          username: ${{ secrets.SERVER_USERNAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          passphrase: ${{ secrets.PASSPHRASE_STAGING }}
          port: 88
          source: target/debug/rust-captcha-verification
          target: ~/

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_STAGING }}
          username: ${{ secrets.SERVER_USERNAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          passphrase: ${{ secrets.PASSPHRASE_STAGING }}
          script: |
            # Delete the old file
            sudo rm /var/api/rust-captcha-verification
          
            # Copy the contents of dist/ to /var/www/
            sudo cp ~/target/debug/rust-captcha-verification /var/api/

            # Copy permissions from html/ to the new files in /var/www/
            sudo chmod +x rust-captcha-verification

            # Delete the old .zip file and unzipped directory
            rm ~/rust-captcha-verification

          port: 88
